### ISSUE TITLE
Conda installation requires SQLAlchemy 1.4

### ISSUE THREAD

**Issue by vant7** [xzkostyan/clickhouse-sqlalchemy#371]
**Describe the bug**
Conda installation requires sqlachemy of 1.4.
Extracting out package informations from [conda-forge](https://anaconda.org/conda-forge/clickhouse-sqlalchemy/files) I see `info/meta.yaml`
```
# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 12 16:00:06 2024
# ------------------------------------------------

package:
  name: clickhouse-sqlalchemy
  version: 0.3.2
source:
  sha256: 267f3a9a1d0d186eb99a41895a684922d31125cea21702cd7dc73af1ccdd10e7
  url: https://pypi.io/packages/source/c/clickhouse-sqlalchemy/clickhouse-sqlalchemy-0.3.2.tar.gz
build:
  noarch: python
  number: '0'
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 hd590300_5
    - ca-certificates 2024.6.2 hbcca054_0
    - ld_impl_linux-64 2.40 hf3520f5_3
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 13.2.0 h77fa898_7
    - libgomp 13.2.0 h77fa898_7
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4ab18f5_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.12.3 hab00c5b_0_cpython
    - readline 8.2 h8228510_1
    - setuptools 70.0.0 pyhd8ed1ab_0
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - wheel 0.43.0 pyhd8ed1ab_1
    - xz 5.2.6 h166bdaf_0
  run:
    - clickhouse-driver >=0.1.2
    - python >=3.6,<4
    - requests
    - sqlalchemy >=1.4,<1.5
test:
  imports:
    - clickhouse_sqlalchemy
    - clickhouse_sqlalchemy.drivers
    - clickhouse_sqlalchemy.drivers.http
    - clickhouse_sqlalchemy.drivers.native
    - clickhouse_sqlalchemy.orm
    - clickhouse_sqlalchemy.sql
about:
  home: https://github.com/xzkostyan/clickhouse-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple ClickHouse SQLAlchemy Dialect
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240612.2.1
  recipe-maintainers:
    - kszucs
    - xzkostyan
  remote_url: https://github.com/conda-forge/clickhouse-sqlalchemy-feedstock
  sha: 48e3237c6c310794de91e48c4ee94fc72f51d273
```
However setup.py specifies 'sqlalchemy>=2.0.0,<2.1.0' which is inconsistent with conda.

**To Reproduce**
Running `conda install 'clickhouse-sqlalchemy==0.3.2' 'sqlalchemy==2.0.14'` fails.

**Expected behavior**
Should be able to install sqlalchemy 2.0 with conda.

**Versions**

- Version of package with the problem.
0.3.2
- Python version
3.12.8
